# Generated by Django 4.2.7 on 2023-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatordevice',
            name='unique_id',
            field=models.CharField(default='abdfa53b-e8d1-46ec-809e-6abb66a0d0bc', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
